### ISSUE TITLE
numpy on windows bug

### ISSUE THREAD

**Issue by CircleOnCircles** [CircleOnCircles/thaifin#2]
```
❯ poetry shell
Spawning shell within C:\Users\n2\Documents\GitHub\intern_2020\.venv
Microsoft Windows [Version 10.0.19042.630]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\n2\Documents\GitHub\intern_2020>python
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from thaifin import
  File "<stdin>", line 1
    from thaifin import
                       ^
SyntaxError: invalid syntax
>>> from thaifin import Stock
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\n2\Documents\GitHub\intern_2020\.venv\lib\site-packages\thaifin\__init__.py", line 1, in <module>
    from thaifin.stock import Stock
  File "C:\Users\n2\Documents\GitHub\intern_2020\.venv\lib\site-packages\thaifin\stock.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\n2\Documents\GitHub\intern_2020\.venv\lib\site-packages\pandas\__init__.py", line 11, in <module>
    __import__(dependency)
  File "C:\Users\n2\Documents\GitHub\intern_2020\.venv\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\n2\Documents\GitHub\intern_2020\.venv\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\n2\\Documents\\GitHub\\intern_2020\\.venv\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

**Comment by CircleOnCircles** [comment]
wait until the upstream fix

https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html

**Comment by CircleOnCircles** [comment]
workaround use `numpy = "1.19.3"` or `thaifin ^0.1.5`
